Repository tricorder-observability/starship, pull requests merged in 2023-02, with the labels that each got.

#49 Cleanup: fix api server resp in deploy api
  src/api-server/http/module_manager.go
Labels: enhancement

#93 Chroe: add mgmt ui build and push pipeline
  .github/workflows/release-dev-images.yaml
Labels: devops, component:ui

#117 Chore: add docker hub push
  .github/workflows/release-dev-images.yaml
Labels: component:cli, component:api-server, component:agent, devops, component:ui

#120 Cleanup: update ci images with docker hub images
  .github/workflows/build-and-test.yml
  .github/workflows/release-dev-images.yaml
  src/api-server/dao/node_agent.go
Labels: devops

#119 refactor(api-server): api-server grpc and http clean
  src/api-server/cmd/main.go
  src/api-server/dao/module.go
  src/api-server/dao/module_instance.go
  src/api-server/dao/module_test.go
  src/api-server/dao/node_agent.go
  src/api-server/grpc/deployer.go
  src/api-server/http/http.go
  src/api-server/http/module_manager.go
  src/api-server/http/module_manager_test.go
Labels: PR:WIP

#130 Cleanup: move static image to docker hub
  devops/base_build_image/build_and_push.sh
  devops/dev_image/Makefile
  devops/dev_image/install.yaml
  devops/release/build_and_push_images.sh
  devops/release/build_and_push_mgmt_ui_image.sh
Labels: devops
